#!/usr/bin/env bash
set -u
cd "$(dirname "$0")"

echo "Damn Right!, pages 1–100 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Damn Right!, pages 1–100"
echo "Damn Right!, pages 101–200 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Damn Right!, pages 101–200"
echo "Damn Right!, pages 201–300 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Damn Right!, pages 201–300"
echo "Damn Right!, pages 301–400 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Damn Right!, pages 301–400"
echo "Damn Right!, pages 401–415 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Damn Right!, pages 401–415"
echo "Poor Charlie's Almanack, pages 1–100 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 1–100"
echo "Poor Charlie's Almanack, pages 101–200 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 101–200"
echo "Poor Charlie's Almanack, pages 201–300 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 201–300"
echo "Poor Charlie's Almanack, pages 301–400 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 301–400"
echo "Poor Charlie's Almanack, pages 401–500 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 401–500"
echo "Poor Charlie's Almanack, pages 501–600 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 501–600"
echo "Poor Charlie's Almanack, pages 601–618 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "Poor Charlie's Almanack, pages 601–618"
echo "The Complete Investor, pages 1–100 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "The Complete Investor, pages 1–100"
echo "The Complete Investor, pages 101–166 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "The Complete Investor, pages 101–166"
echo "All I Want to Know, pages 1–100 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "All I Want to Know, pages 1–100"
echo "All I Want to Know, pages 101–200 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "All I Want to Know, pages 101–200"
echo "All I Want to Know, pages 201–245 | model: sonnet | effort: high"
claude -p --model sonnet --effort high --permission-mode acceptEdits "All I Want to Know, pages 201–245"
